version: '3'
services:
  website:
    env_file:
     - .env
    image: ${CONTAINER_IMAGE_NAME}
    ports:
      - 3000:3000
    networks:
      - website
    environment:
      WEBSITE_DB_HOST: db:3306
      WEBSITE_DATABASE: ${WEBSITE_DB_NAME}
      WEBSITE_DB_USER: ${WEBSITE_DB_USER}
      WEBSITE_DB_PASSWORD: ${WEBSITE_DB_PW}
    depends_on:
      - db
    links:
      - db:mysql

  db:
    image: mysql:latest
    env_file:
     - .env
    networks:
      - website
    environment:
      MYSQL_ROOT_PASSWORD: ${WEBSITE_DB_PW}
      MYSQL_USER: ${WEBSITE_DB_USER}
      MYSQL_DATABASE: ${WEBSITE_DB_NAME}

networks:
  website:
    external: false

