version: '3'
services:
  website:
    tty: true
    env_file:
     - .env
    image: ${CONTAINER_IMAGE_NAME}
    networks:
      - website
    ports:
      - 3000:3000
    environment:
      WEBSITE_DB_HOST: ${WEBSITE_DB_HOST}
      WEBSITE_DATABASE: ${WEBSITE_DB_NAME}
      WEBSITE_DB_USER: ${WEBSITE_DB_USER}
      WEBSITE_DB_PASSWORD: ${WEBSITE_DB_PW}
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
     - .env
    networks:
      - website
    environment:
      MYSQL_ROOT_PASSWORD: ${WEBSITE_DB_PW}
      MYSQL_ROOT_USER: ${WEBSITE_DB_USER}
      MYSQL_DATABASE: ${WEBSITE_DB_NAME}
    volumes:
      - /data/dev/db:/var/lib/mysql


networks:
  website:
    external: false

